enum AppConstants {
  bearer('Bearer'),
  applicationJson('application/json'),
  multipartFormData('multipart/form-data'),
  contentType('application/json'),
  accept('application/json'),
  android('android'),
  ios('ios'),
  en('en'),
  bn('bn'),
  userId('userId'),
  token('token'),
  language('language'),
  yyyyMmDd('dd-MM-yyyy'),
  ddMmYyyy('dd/MM/yyyy'),
  ddMmYyyySlash('dd/MM/yyyy'),
  dMmmYHm('d MMMM y hh:mm a'),
  dMmmY('d MMM y'),
  dMmY('d MMM y'),
  yyyyMm('yyyy-MM'),
  mmm('mmm'),
  mmmm('mmmm'),
  mmmmY('mmmmY'),
  isSwitched('isSwitched'),
  deviceId('deviceId'),
  deviceOs('deviceOs'),
  userAgent('userAgent'),
  appVersion('appVersion'),
  buildNumber('buildNumber'),
  ipnUrl('ipnUrl'),
  storeId('storeId'),
  storePassword('storePassword'),
  mobile('mobile'),
  email('email'),
  pushId('pushId'),
  refreshToken('refreshToken'),
  accessToken('accessToken'),
  fontFamily('fontFamily'),
  loginResponse('loginResponse'),
  cashCartItems('cashCartItems'),
  isDarkMode('isDarkMode'),
  username('username');

  final String key;
  const AppConstants(this.key);
}
